from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name='DevicePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=20, unique=True)),
                ('plan_tier', models.CharField(max_length=20, default='standard')),
                ('hourly_rate', models.DecimalField(max_digits=6, decimal_places=2)),
                ('daily_rate', models.DecimalField(max_digits=6, decimal_places=2)),
                ('weekly_rate', models.DecimalField(max_digits=8, decimal_places=2)),
                ('monthly_rate', models.DecimalField(max_digits=8, decimal_places=2)),
                ('speed_limit_mbps', models.IntegerField(default=10)),
                ('data_cap_gb', models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('data_mb', models.IntegerField()),
                ('duration_hours', models.IntegerField()),
                ('price', models.DecimalField(max_digits=8, decimal_places=2)),
                ('speed_limit_mbps', models.IntegerField(default=10)),
                ('device_type', models.CharField(max_length=20, blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=7, default='#00d4ff')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['price']},
        ),
        migrations.CreateModel(
            name='RouterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('router_ip', models.CharField(max_length=15, default='192.168.8.1')),
                ('router_user', models.CharField(max_length=50, default='admin')),
                ('router_pass', models.CharField(max_length=100, default='admin')),
                ('router_type', models.CharField(max_length=20, default='hilink')),
                ('auto_block', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, null=True)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField(null=True, blank=True)),
                ('device_type', models.CharField(max_length=20, default='smartphone')),
                ('device_name', models.CharField(max_length=100, blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('balance', models.DecimalField(max_digits=10, decimal_places=2, default=0.00)),
                ('package_data_used_mb', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('package_expires_at', models.DateTimeField(null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(null=True, blank=True)),
                ('plan', models.ForeignKey('DevicePlan', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='users')),
                ('active_package', models.ForeignKey('DataPackage', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True, related_name='active_users')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='PackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('amount_paid', models.DecimalField(max_digits=8, decimal_places=2)),
                ('method', models.CharField(max_length=10, default='mpesa')),
                ('mpesa_code', models.CharField(max_length=20, blank=True, null=True)),
                ('reference', models.CharField(max_length=50, unique=True, blank=True)),
                ('status', models.CharField(max_length=10, default='pending')),
                ('activated_at', models.DateTimeField(null=True, blank=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True)),
                ('data_used_mb', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey('User', on_delete=django.db.models.deletion.CASCADE, related_name='purchases')),
                ('package', models.ForeignKey('DataPackage', on_delete=django.db.models.deletion.PROTECT)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True, blank=True)),
                ('duration_minutes', models.IntegerField(default=0)),
                ('data_used_mb', models.DecimalField(max_digits=10, decimal_places=2, default=0)),
                ('amount_billed', models.DecimalField(max_digits=8, decimal_places=2, default=0)),
                ('ip_address', models.GenericIPAddressField(null=True, blank=True)),
                ('status', models.CharField(max_length=10, default='active')),
                ('user', models.ForeignKey('User', on_delete=django.db.models.deletion.CASCADE, related_name='sessions')),
                ('package_purchase', models.ForeignKey('PackagePurchase', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True)),
            ],
            options={'ordering': ['-start_time']},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(max_digits=10, decimal_places=2)),
                ('method', models.CharField(max_length=10, default='mpesa')),
                ('status', models.CharField(max_length=10, default='pending')),
                ('reference', models.CharField(max_length=50, unique=True, blank=True)),
                ('mpesa_code', models.CharField(max_length=20, blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(null=True, blank=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey('User', on_delete=django.db.models.deletion.CASCADE, related_name='payments')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='RouterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=17, blank=True)),
                ('ip', models.CharField(max_length=15, blank=True)),
                ('detail', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey('User', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=160, blank=True)),
                ('category', models.CharField(max_length=10, default='hourly')),
                ('duration_value', models.PositiveIntegerField(default=1)),
                ('duration_unit', models.CharField(max_length=10, default='hours')),
                ('data_mb', models.IntegerField(default=0)),
                ('speed_mbps', models.IntegerField(default=10)),
                ('price', models.DecimalField(max_digits=8, decimal_places=2)),
                ('old_price', models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)),
                ('color', models.CharField(max_length=7, default='#00d4ff')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('linked_package', models.ForeignKey('DataPackage', on_delete=django.db.models.deletion.SET_NULL, null=True, blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={'ordering': ['sort_order', 'price']},
        ),

        migrations.AddField(
            model_name='routersettings',
            name='ssid',
            field=models.CharField(max_length=64, default='NetPulse Wi-Fi', help_text='Wi-Fi network name shown on portal'),
        ),
    ]
