from django.urls import path
from . import views

urlpatterns = [
    path('auth/login/', views.login),
    path('auth/register/', views.register),
    path('auth/me/', views.me),
    path('auth/claim-blue-badge/', views.claim_blue_badge),
    path('auth/submit-verification/', views.submit_verification),
    path('auth/apply-verification/', views.apply_verification),
    path('profile/update/', views.update_profile),
    path('profile/<int:user_id>/', views.user_profile),
    path('profile/<int:user_id>/follow/', views.follow_user),
    path('profile/<int:user_id>/videos/', views.user_videos),
    path('profile/u/<str:username>/', views.user_profile_by_username),
    path('profile/u/<str:username>/follow/', views.follow_user_by_username),
    path('profile/u/<str:username>/videos/', views.user_videos_by_username),
    path('feed/', views.feed),
    path('videos/upload/', views.upload_video_v2),
    path('videos/<int:video_id>/delete/', views.delete_video),
    path('videos/<int:video_id>/like/', views.like_video),
    path('videos/<int:video_id>/view/', views.view_video),
    path('videos/<int:video_id>/save/', views.save_video),
    path('videos/<int:video_id>/comments/', views.comments),
    path('search/', views.search),
    path('notifications/', views.notifications),
    path('ads/', views.active_ads),
    path('ads/<int:ad_id>/view/', views.record_ad_view),
    path('earnings/withdraw/', views.request_withdrawal),
    # Admin endpoints
    path('admin/stats/', views.admin_stats),
    path('admin/users/', views.admin_users),
    path('admin/users/<int:user_id>/suspend/', views.admin_suspend_user),
    path('admin/users/<int:user_id>/monetize/', views.admin_monetize_user),
    path('admin/verification-requests/', views.admin_verification_requests),
    path('admin/verification-requests/<int:req_id>/approve/', views.admin_approve_verification),
    path('admin/verification-requests/<int:req_id>/reject/', views.admin_reject_verification),
    path('admin/settings/', views.admin_settings),
    path('admin/users/<int:user_id>/verify/', views.admin_verify_user),
    path('admin/ads/', views.admin_manage_ads),
    path('admin/ads/<int:ad_id>/toggle/', views.admin_toggle_ad),
    path('admin/ads/<int:ad_id>/delete/', views.admin_delete_ad),
]
